# Generated by Django 4.0.6 on 2023-03-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=256, null=True)),
                ('name_ru', models.CharField(max_length=256, null=True)),
                ('name_en', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subctg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=256, null=True)),
                ('name_ru', models.CharField(max_length=256, null=True)),
                ('name_en', models.CharField(max_length=256, null=True)),
                ('ctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.category')),
            ],
        ),
    ]
