# Generated by Django 4.0.6 on 2023-03-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_category_subctg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subctg',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subctg',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='subctg',
            name='name_uz',
        ),
    ]
